var TMDB_FIELD_DICT = {
    id: 'ID',
    title: '标题',
    name: '名称',
    original_title: '原始标题',
    original_name: '原始名称',
    release_date: '上映日期',
    first_air_date: '首播日期',
    overview: '简介',
    tagline: '标语',
    status: '状态',
    runtime: '时长(分钟)',
    episode_run_time: '单集时长(分钟)',
    vote_average: '评分',
    vote_count: '投票数',
    popularity: '热度',
    budget: '预算',
    revenue: '票房',
    homepage: '官网',
    imdb_id: 'IMDB ID',
    adult: '成人内容',
    genres: '类型标签',
    genre_ids: '类型ID列表',
    production_companies: '制片公司',
    production_countries: '制片国家',
    origin_country: '来源国家',
    original_language: '原始语言',
    spoken_languages: '对白语言',
    release_dates: '发行日期',
    belongs_to_collection: '所属合集',
    content_ratings: '内容分级',
    number_of_seasons: '总季数',
    number_of_episodes: '总集数',
    seasons: '季信息',
    networks: '播出平台',
    created_by: '创作者',
    type: '节目类型',
    in_production: '制作中',
    last_air_date: '最后播出日',
    next_episode_to_air: '下集预告',
    episode_groups: '剧集分组',
    backdrop_path: '背景图',
    poster_path: '海报',
    videos: '视频',
    images: '图片',
    credits: '演职人员',
    cast: '演员',
    crew: '幕后人员',
    external_ids: '外部ID',
    keywords: '关键词',
    recommendations: '推荐',
    similar: '相似作品',
    reviews: '评论',
    alternative_titles: '别名',
    translations: '翻译',
    changes: '变更日志',
    poster: '海报图'
};

var TMDB_FIELD_GROUPS = [
    { key: 'basic', label: '基本信息', fields: ['id', 'title', 'name', 'original_title', 'original_name', 'release_date', 'first_air_date', 'overview', 'tagline', 'status', 'runtime', 'episode_run_time', 'vote_average', 'vote_count', 'popularity', 'budget', 'revenue', 'homepage', 'imdb_id', 'adult'] },
    { key: 'genres', label: '类型标签', fields: ['genres', 'genre_ids'] },
    { key: 'production', label: '制片信息', fields: ['production_companies', 'production_countries', 'origin_country', 'original_language', 'spoken_languages'] },
    { key: 'release', label: '发行信息', fields: ['release_dates', 'belongs_to_collection', 'content_ratings'] },
    { key: 'tv', label: '剧集信息', fields: ['number_of_seasons', 'number_of_episodes', 'seasons', 'networks', 'created_by', 'type', 'in_production', 'last_air_date', 'next_episode_to_air', 'episode_groups'] },
    { key: 'media', label: '媒体资源', fields: ['backdrop_path', 'poster_path', 'videos', 'images'] },
    { key: 'people', label: '演职人员', fields: ['credits', 'cast', 'crew'] },
    { key: 'other', label: '其他信息', fields: ['external_ids', 'keywords', 'recommendations', 'similar', 'reviews', 'alternative_titles', 'translations', 'changes'] }
];

var TMDB_STATUS_DICT = {
    'Rumored': '传闻',
    'Planned': '计划中',
    'In Production': '制作中',
    'Post Production': '后期制作',
    'Released': '已上映',
    'Canceled': '已取消',
    'Pilot': '试播集',
    'Ending': '即将完结',
    'Returning Series': '续订中'
};

function getTmdbFieldLabel(key) {
    return TMDB_FIELD_DICT[key] || key;
}
