"""Shared task organization state constants without feature-layer imports."""

TASK_KIND_IMPORT = "IMPORT"
TASK_KIND_REORGANIZE = "REORGANIZE"
ORGANIZATION_FALLBACK_PENDING = "FALLBACK_PENDING"
ORGANIZATION_ORGANIZED = "ORGANIZED"

__all__ = [
    "TASK_KIND_IMPORT",
    "TASK_KIND_REORGANIZE",
    "ORGANIZATION_FALLBACK_PENDING",
    "ORGANIZATION_ORGANIZED",
]
